### ISSUE TITLE
It will be redis auth plugin ?

### ISSUE THREAD

**Issue by Prots** [emqtt/emqttd_plugin_redis#1]
It will be redis auth plugin or just a simple template how connect to redis from emqttd?

I think it is not a problem write a plugin with eredis and pooler for connecting  with redis, but write an auth redis plugin is more complicated task.

**Comment by erylee** [comment]
@Prots, okay, I write a skeleton for this plugin this week.

**Comment by erylee** [comment]
First release of the redis plugin.
