### ISSUE TITLE
how to define ACL that maps user to topic

### ISSUE THREAD

**Issue by 87sanchavan** [emqtt/emqttd_plugin_redis#2]
Hi ,

I have successfully configured Redis with emqttd. 
For Authentication , I have added with below query in Redis and it is working
HSET mqtt_user:sanjay password 'pass123'

For ACL , I have added with below query where c/d is topic name , however it is not working..
        SADD mqtt_acl:sanjay "c/d"

I guess we need to add permission (read , write , readandwrite) value to this topic to make it work but not sure what is exact format (E.g c/d:1).

Can you please tell me how to add ACL for given user and topic.

Thanks
Sanjay

**Comment by wangtao9090** [comment]
iI have the same problem, do you have to solve this problem?

**Comment by 87sanchavan** [comment]
yes... I solved this problem... Do you want to know how I solved it?

**Comment by erylee** [comment]
Hi @87sanchavan, The ACL Rules:

```
SADD mqtt_acl:sanjay "publish c/d"
SADD mqtt_acl:sanjay "subscribe x/y"
SADD mqtt_acl:sanjay "pubsub foo/bar"
```

I will upgrade this plugin later:)

**Comment by erylee** [comment]
Please check the latest README.md
