### ISSUE TITLE
username and clientID authentication using Redis Plug

### ISSUE THREAD

**Issue by yinweinidongle** [emqtt/emqttd_plugin_redis#4]
Hey,lee,
I have username in the redis database,and it works,but what about clientID,how I set clentID with Redis,can you please help me with this issue?

**Comment by anhldbk** [comment]
@emqplus Any plan to support authentication with clientID?

Anyway, thank you for this great broker! Do your best.

**Comment by emqplus** [comment]
Hi @anhldbk, I will add the '%c' variable in 1.1 release. Thanks.

**Comment by emqplus** [comment]
@anhldbk, the '%c' variable has been supported in 1.1 release
